### ISSUE TITLE
I am unable to display html text in highlighter.

### ISSUE THREAD

**Issue by viveksApp** [bvaughn/react-highlight-words#101]
I am unable to display html text in highlighter. For e.g. Hi there \n How are you.

**Comment by sergei-startsev** [comment]
@viveksApp I don't see HTML in your example. Is there a chance to provide a sandbox with the issue?

**Comment by viveksApp** [comment]
@sergei-startsev Thanks for replying. Here is my link of Sandbox   [https://codesandbox.io/s/magical-estrela-wffgyl?file=/src/App.js](url) 
In this code i am using html tags like <br/> and <h1>, i want they should work as usual html output not as a string.
Thanks in advance for your help

**Comment by sergei-startsev** [comment]
@viveksApp It's by design. `react-highlight-words` doesn't support markup. Text chunks are passed as `children` to `createElement` and React escapes them. Check out https://codesandbox.io/s/dazzling-brattain-gm7xsj.

**Comment by viveksApp** [comment]
@sergei-startsev Thanks for replying, the highlighter is very crucial part of upcoming project, as this plugin not supporting the HTML, still it is excellent plugin for highlighting. No worry, i will use this plugin in my some another project.
Thanks for you valuable time .. have a great time
