### ISSUE TITLE
Highlight only entire words instead of partial words

### ISSUE THREAD

**Issue by italodeandra** [bvaughn/react-highlight-words#104]
![image](https://user-images.githubusercontent.com/19225266/226707241-66c43a25-2996-42d5-ac30-f1db53c29243.png)

I asked to highlight `experince` but I don't want it to highlight `experienced`. Is is possible?

**Comment by sergei-startsev** [comment]
@italodeandra you can either pass regex string as search word (e.g. `experience\\b`) or pass custom `findChunks` function (see examples in readme)
