### ISSUE TITLE
Is it not possible to utilize multiple highlight colors?

### ISSUE THREAD

**Issue by thejtrann** [bvaughn/react-highlight-words#106]
If we wanted to use different highlight colors for different searchWords, would this be possible?

**Comment by nrgbistro** [comment]
I'm using the custom component and have had success changing the highlight color. However, I'm confused what the `highlightIndex` actually means. I have the following `searchWords` array:

`['Minimally', 'Spinal', 'Surgery', 'Fusion']`

The first 3 should be highlighted in yellow, the last word should be highlighted in red. I'm passing in the index where words switch from yellow to red (>= 3), but for some reason the `highlightIndex` is different from my array index:


```
highlightIndex 0 Minimally
highlightIndex 1 Spinal
highlightIndex 2 Fusion
highlightIndex 3 Surgery
```

Why would `Fusion` have an index of 2 and `Surgery` have an index of 3? This breaks the functionality of my highlighter component.

**Comment by sergei-startsev** [comment]
@nrgbistro `highlightIndex` is the index of matched text:

![Image](https://github.com/user-attachments/assets/e041a2e1-8097-4806-9ff1-00f4355816da)

**Comment by nrgbistro** [comment]
I see, so is there any way to achieve what I'm looking for without manually matching words within my component? I would like to be able to highlight the first part of my `searchWords` array one color, and the rest another color, regardless of where the matches show up in the `textToHighlight`

**Comment by sergei-startsev** [comment]
Are there any issues with looking up the child in your `searchWords`?
