### ISSUE TITLE
Access active element

### ISSUE THREAD

**Issue by randrei12** [bvaughn/react-highlight-words#107]
Is there anyway (like a ref or something) to access the active highlighted element? I need to scroll to the new active element each time the activeIndex changes.

**Comment by sergei-startsev** [comment]
@randrei12 would it be possible to select the active element by CSS class passed as `activeClassName` prop?

**Comment by randrei12** [comment]
Most of the times it returns null. But I was able to do what I wanted using custom component as the highlightTag. Forgot to close the issue tho.

**Comment by decipher-cs** [comment]
> Most of the times it returns null. But I was able to do what I wanted using custom component as the highlightTag. Forgot to close the issue tho.

Can you elaborate on how you achieved this? I am also trying to figure out a way to auto-scroll to the active highlight.

**Comment by randrei12** [comment]
I ended up using a custom react component in which I wrote the logic.
