### ISSUE TITLE
Crashes when adding [ or \ characters to search string

### ISSUE THREAD

**Issue by KrisjanisStrods** [bvaughn/react-highlight-words#110]

**Comment by Avataw** [comment]
I've just stumbled upon this very issue - why is this autoEscape not default to true? :) 
This seemed quite unintuitive.

**Comment by sergei-startsev** [comment]
> I've just stumbled upon this very issue - why is this autoEscape not default to true? :) This seems quite unintuitive.
We may consider it for the next major release.
