### ISSUE TITLE
Add motivation of package

### ISSUE THREAD

**Issue by stephan-noel** [bvaughn/react-highlight-words#113]
I was looking into this problem and trying to figure out why this is a complicated problem and has motivated other packages.  First I saw the core library mentioned in [reach ui's combobox](https://github.com/reach/reach-ui/blob/main/packages/combobox/src/utils.ts), and then I dug up [Sophie's solution](https://github.com/facebook/react/issues/3386#issuecomment-78605760) (copied below): 

```jsx
var parts = "I am a cow; cows say moo. MOOOOO.".split(/(\bmoo+\b)/gi);
for (var i = 1; i < parts.length; i += 2) {
  parts[i] = <span className="match" key={i}>{parts[i]}</span>;
}
return <div>{parts}</div>;
```

I saw that the behavior described by Sophie seems to be guaranteed and mentioned [here in the MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split#splitting_with_a_regexp_to_include_parts_of_the_separator_in_the_result). 

I'm trying to get some clarity on this problem and if there are some edge cases with Sophie's solution which aren't being addressed and why this has led to so many different attempts (see comments after Sophie's) to do this.  I think this would be helpful for others to know as well and I'd be happy to add this information to the project README to increase visibility if you agree.

**Comment by sergei-startsev** [comment]
@stephan-noel if you have some specific cases you'd like to list in the motivation section, I'd be happy to review them.

**Comment by stephan-noel** [comment]
@sergei-startsev thank you for that.  That's my problem though, I don't know when I should use this library or [highlight-words-core](https://www.npmjs.com/package/highlight-words-core), and when something simple like the following is good enough:

```jsx
var parts = "I am a cow; cows say moo. MOOOOO.".split(/(\bmoo+\b)/gi);
for (var i = 1; i < parts.length; i += 2) {
  parts[i] = <span className="match" key={i}>{parts[i]}</span>;
}
return <div>{parts}</div>;
```

I looked through the code of [the core](https://github.com/bvaughn/highlight-words-core/blob/master/src/utils.js) and it's way more complicated than this..  So I'm not sure when I need this more complicated approach and why.

**Comment by sergei-startsev** [comment]
You can start with the list of [supported properties](https://github.com/bvaughn/react-highlight-words?tab=readme-ov-file#props) to better understand possible use/edge cases. If you're happy with the solution above, you don't need anything else.
