### ISSUE TITLE
module not working in Nextjs 14

### ISSUE THREAD

**Issue by hrit2773** [bvaughn/react-highlight-words#116]
I am trying to import react-highlight-words in my nextjs 14 app but its unable to recognise. I have installed it using npm i command.

**Comment by sergei-startsev** [comment]
@hrit2773 would you mind to create a repo to reproduce the issue?

**Comment by yogithesymbian** [comment]
Highlighter Module not found: Can't resolve 'react-highlight-words'
```
import Highlighter from 'react-highlight-words';

type InputRef = GetRef<typeof Input>;
```

**Comment by yogithesymbian** [comment]
> Highlighter **Module not found: Can't resolve 'react-highlight-words'**
> 
> ```
> import Highlighter from 'react-highlight-words';
> 
> type InputRef = GetRef<typeof Input>;
> ```

```
npm i @types/react-highlight-words
...
"dependencies": {
    "@types/react-highlight-words": "^0.16.7",
```

**Comment by sergei-startsev** [comment]
@yogithesymbian you import 'react-highlight-words 'while installing the package with types: 
>npm i **@types**/react-highlight-words

**Comment by sergei-startsev** [comment]
Closing the issue to reduce irrelevant discussion. If you still face issues with the package in Next.js, feel free to create a new issue with a link to a sandbox that will allow to reproduce them.

**Comment by yogithesymbian** [comment]
> @yogithesymbian you import 'react-highlight-words 'while installing the package with types: 
> >npm i **@types**/react-highlight-words

i have tried `rm -rf node modules` and `npm install` again and `npm run dev` the error still occurs module not found. laters will try on sandbox maybe the projects is broken or something dunno why .
