### ISSUE TITLE
Allow markup in textToHighlight prop

### ISSUE THREAD

**Issue by blessenm** [bvaughn/react-highlight-words#15]
I have a use case where I have a chat interface where each messages can contain markup like links.
I use this component to highlight search term within messages.

Right now markup is escaped and I modified the component to for my use case.

```
const output = chunks.map((chunk, index) => {
    const text = textToHighlight.substr(chunk.start, chunk.end - chunk.start)

    if (chunk.highlight) {
      let highlightClasses = classnames( highlightClassName , { 
        active: highlightCount == activeHighlightIndex 
      });
      highlightCount++;
      return (
         `<mark class="${highlightClasses}">${text}</mark>`
      )
    } else {
      return (
        `${text}`
      )
    }
  });
  return <span dangerouslySetInnerHTML={{__html: output.join('')}}></span>;
```

For this to work properly, I had to modify the `highlight-words-core` package to ignore markup while doing a search. **[Here is the separate issue for that.](https://github.com/bvaughn/highlight-words-core/issues/1)**

It would be great if this feature could be included. I could work on a PR if you agree on this.

**Comment by bvaughn** [comment]
Hey @blessenm,

Thanks for creating an issue. I'm not really a fan of replacing JSX with template strings and using `dangerouslySetInnerHTML`.

Could you give me an example of your `textToHighlight` and your `searchWords` so I could better understand the problem?

**Comment by blessenm** [comment]
Well I have some message in an array like

    const messages = [
      'Can you tell me what brand and style you like?',
      'Im into Hugo Boss https://www.zalando.de/hugo/ '
    ];

So I first run a map function on the message array through [Autolinker](https://www.npmjs.com/package/autolinker.js/). And this outputs

    const linkedMessages = [
       'Can you tell me what brand and style you like?',
       'Im into Hugo Boss <a href="https://www.zalando.de/hugo/">https://www.zalando.de/hugo/</a>'
    ];

Now I run another map with `react-highlight-words` to render the final output. The default behaviour will escape all the markup and mess up the matching.

    linkedMessages.map(msg => {
      return <Highlighter
        highlightClassName='match'
        searchWords={['hugo']}
        textToHighlight={msg}
      />;
    });
    
I hope you understand my use case. I also didn't want to go with the `dangerouslySetInnerHTML ` route but I couldn't figure out another way.

**Comment by bvaughn** [comment]
Thank you for elaborating. 😄

I've given it a little thought and I think what you're describing is a bit outside of the scope of this library. I intended this library for simple text-substring-matching. I'd rather avoid use of `dangerouslySetInnerHTML` or complicating the implementation.

Feel free to fork though. I would be happy to see a more flexible alternative to become available. 😁

Going to close this issue for now since I don't intend to support this. Hope you understand and thanks again for the detailed feature request!

**Comment by softmarshmallow** [comment]
how did you solve this problem?

**Comment by LarryCChien** [comment]
> how did you solve this problem?

Maybe it's not best practice.
I use `renderToString` from [renderToString – React](https://react.dev/reference/react-dom/server/renderToString) to solve this problem:

```js
import { renderToString } from 'react-dom/server'
import Highlighter from 'react-highlight-words'

const highlightedContentText = ({ content, searchWords }) => {
  return renderToString(
    <Highlighter
      searchWords={searchWords}
      textToHighlight={content}
    />,
  ))
}

const HighlightContent = ({ content, searchWords }) => {
  <div
    dangerouslySetInnerHTML={{
      __html: highlightedContentText({
        content,
        searchWords,
      }),
    }}
  />
}
```
