### ISSUE TITLE
Doc needs "how to import Highlighter after installing with npm"

### ISSUE THREAD

**Issue by kevart** [bvaughn/react-highlight-words#16]
`import Highlighter from './Highlighter'`
Cannot resolve 'file' or 'directory' ./Highlighter

**Comment by bvaughn** [comment]
Your bundler should be requiring NPM package relative to `node_modules`. So in this case...
```js
import Highlighter from 'react-highlight-words';
// or
const Highlighter = require('react-highlight-words');
```
This isn't specific to this lib, but if you think docs can be improved please feel free to submit a PR. 😄

**Comment by kevart** [comment]
remote: Permission to bvaughn/react-highlight-words.git denied to kevart.

**Comment by bvaughn** [comment]
https://help.github.com/articles/fork-a-repo/ 😄
