### ISSUE TITLE
Warning on proptypes when a regex is passed as searchWords item

### ISSUE THREAD

**Issue by franciscopuyo** [bvaughn/react-highlight-words#17]
Hi, how are you?
I'm having a warning message from proptype validation when I pass a regex as a proptype validation.

`Warning: Failed prop type: Invalid prop searchWords[0]of type regexp supplied to Highlighter, expected string.`

Anyway, with the regex, the component higlights the correct words, so its working well. 

Could you add regex as a proptype (i think it would be React.PropTypes.object) so the warning is not displayed anymore?

Thank you

**Comment by bvaughn** [comment]
Hi @franciscopuyo,

Would you be interested in contributing a PR with this change (and a new unit test)?

**Comment by franciscopuyo** [comment]
Yes @bvaughn, I'll be working on that

**Comment by bvaughn** [comment]
🙇  Thanks!
