### ISSUE TITLE
Highlight using cursor

### ISSUE THREAD

**Issue by yarnball** [bvaughn/react-highlight-words#23]
Hi,

Great work on this.

I'm wondering if it's possible to highlight using the cursor, instead of searching the text manually. I'd imagine there would have to be a data store of sorts for it to store what you've highlighted persistently.

How might this be possible using your repo?

Thanks

**Comment by bvaughn** [comment]
Thank you! 🙇 

If I understand you correctly, you could implement something like this yourself using this library by automatically passing it a `searchWords` prop that is whatever the currently-cursor-focused word is.

This is not something I have any intentions of adding to the library though. 😄 This project was kind of a for-fun effort but not something I'm actively investing time into at this point. Hope you understand!
