### ISSUE TITLE
Scroll active index into view

### ISSUE THREAD

**Issue by tiffon** [bvaughn/react-highlight-words#24]
Would be nice if this supported an option to scroll the active index into view.

Very cool component.

**Comment by bvaughn** [comment]
Hey @tiffon,

Thanks for the compliment 😄

I don't actively work on this component anymore. If you'd like to submit a PR adding this feature I'll be happy to review it and give it consideration. I won't be building it though because I just don't have the time.

Cheers!

**Comment by bvaughn** [comment]
Closing due to disinterest. I'd be happy to review a PR though. 😄
