### ISSUE TITLE
react.PropTypes will be removed in V16

### ISSUE THREAD

**Issue by Fasani** [bvaughn/react-highlight-words#30]
I noticed the following warning with a newer version of React which I installed today.

~/react-highlight-words/dist/main.js

Line: 90
```
Highlighter.propTypes = {
	  activeClassName: _react.PropTypes.string,
	  activeIndex: _react.PropTypes.string,
	  autoEscape: _react.PropTypes.bool,
	  highlightClassName: _react.PropTypes.string,
	  highlightTag: _react.PropTypes.string,
	  highlightStyle: _react.PropTypes.object,
	  searchWords: _react.PropTypes.arrayOf(_react.PropTypes.string).isRequired,
	  textToHighlight: _react.PropTypes.string.isRequired,
	  sanitize: _react.PropTypes.func
	};
```

Creates the following warning:
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by Fasani** [comment]
If you wish, I don't mind updating the project and sending a PR.

**Comment by Fasani** [comment]
Actually, I can see the project is already updated but via NPM it seemed to load 0.6.0. I have updated to 0.8.0 and this issue is now closed.

**Comment by bvaughn** [comment]
Thanks for the follow up :)
