### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by DrGor** [bvaughn/react-highlight-words#31]
Is react 16 supported ? If yes, then could you please update the `peerDependencies` for `package.json` ?

**Comment by bvaughn** [comment]
Give it a shot and see. Shoot me a PR with the peer deps bump if it works.
:)

**Comment by DrGor** [comment]
Works like a charm.
https://github.com/bvaughn/react-highlight-words/pull/32

**Comment by bvaughn** [comment]
> Kindly reminding that a new version needs to be generated if you accept it.

Yes 😉 

Published as 0.8.1.

Thanks!
