### ISSUE TITLE
Case sensitivity flag? 

### ISSUE THREAD

**Issue by Is0tope** [bvaughn/react-highlight-words#34]
I could not find one in the docs. Is this something intentional, or could I add a pull request?

**Comment by bvaughn** [comment]
Not really intentional. You can submit a PR if you'd like. 😄

**Comment by bvaughn** [comment]
I'll do this. I have a few minutes.

**Comment by bvaughn** [comment]
react-highlight-words@0.10.0 and highlight-words-core@1.1.0 have been released with support for this.
