### ISSUE TITLE
Null `textToHighlight` causes exception

### ISSUE THREAD

**Issue by RichardBradley** [bvaughn/react-highlight-words#36]
I have some properties which are nullable, which I want to highlight.
Currently, `<Highlight>` will throw an exception if `textToHighlight` is null, forcing me to do:

                                        <Highlighter
                                            searchWords={[this.state.nameFilterText]}
                                            autoEscape="true"
                                            textToHighlight={entity.name || ""}
                                        />

I think it would be slightly nicer (and [robust](https://en.wikipedia.org/wiki/Robustness_principle)) if the library accepted null input and produced null output (or "").

(Thanks for a great lib!)

**Comment by bvaughn** [comment]
The prop is marked in the docs and prop-types as being a _required string_

I guess I'd be open to accepting a PR that defaults `undefined` values to "" but a `null` value seems more intentional. I think it's reasonable for users of the library to have to do the `|| ""` in this case. 😄

**Comment by RichardBradley** [comment]
Fair enough.
Give me a few days to see if I get around to creating a PR for this, otherwise I'll have to make do with `|| ""`

**Comment by bvaughn** [comment]
Sure

**Comment by bvaughn** [comment]
Thanks a ton for this contribution! Just published as 1.1.1
