### ISSUE TITLE
Version number in npm package (0.10.0) does not match repo (0.9.0)

### ISSUE THREAD

**Issue by ZhangYiJiang** [bvaughn/react-highlight-words#38]
[According to npm](https://www.npmjs.com/package/react-highlight-words), the current version is 0.10.0, released two weeks ago, but the code in this repo is only for version 0.9.0, and there weren't any commits from two weeks ago.

**Comment by bvaughn** [comment]
Just forgot to push. I'm the only one that works on this repo so ti's easy to overlook. Just pushed.
