### ISSUE TITLE
How to run the tests?

### ISSUE THREAD

**Issue by RichardBradley** [bvaughn/react-highlight-words#39]
I appreciate that most of this probably isn't your problem, but I was hoping you'd have some advice.

I am trying to run the tests for `react-highlight-words`, so that I can hack on #36 and #12

I can't run the tests on CentOS 7, as I am missing `libSSL 1.0.0` and cannot install that version.

### First attempt: Windows

First, I tried to install the project on Windows with `npm install`, but I get:

```
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-highlight-words@0.10.0 build:website: `npm run clean:website && NODE_ENV=production webpack --config webpack.config.website.js -p --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-highlight-words@0.10.0 build:website script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I think that the windows shell doesn't like commands like `NODE_ENV=test karma start`

### Second attempt: CentOS 7

Never mind, I switched to a CentOS 7 VM and tried again.

Now I get:

```
$ npm install
....
$ npm test
...
09 11 2017 14:27:21.069:INFO [launcher]: Starting browser PhantomJS2
09 11 2017 14:27:21.082:ERROR [launcher]: Cannot start PhantomJS2
...
09 11 2017 14:27:21.219:ERROR [launcher]: PhantomJS2 failed 2 times (cannot start). Giving up.
npm ERR! Test failed.  See above for more details.
```

(with no diagnostic info, which is unhelpful).

So I tried to find out what's wrong with `PhantomJS2`:

```
$ find * -name phantomjs
node_modules/karma-phantomjs2-launcher/node_modules/phantomjs2-ext/bin/phantomjs
node_modules/karma-phantomjs2-launcher/node_modules/phantomjs2-ext/lib/phantom/bin/phantomjs
node_modules/karma-phantomjs2-launcher/node_modules/.bin/phantomjs
node_modules/phantomjs2/bin/phantomjs
node_modules/phantomjs2/lib/phantom/bin/phantomjs
node_modules/img-stats/test/phantomjs
node_modules/.bin/phantomjs
$ node_modules/karma-phantomjs2-launcher/node_modules/phantomjs2-ext/bin/phantomjs
/home/vagrant/react-highlight-words/node_modules/karma-phantomjs2-launcher/node_modules/phantomjs2-ext/lib/phantom/bin/phantomjs: error while loading shared l
ibraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

(This is after installing `fontconfig`, `openssl` and `libssh`)

I do have libssl, but not that version:

```
$ ls -l /usr/lib64/libssl*
-rwxr-xr-x. 1 root root 315072 May 30 15:31 /usr/lib64/libssl3.so
lrwxrwxrwx. 1 root root     16 Nov  9 14:20 /usr/lib64/libssl.so.10 -> libssl.so.1.0.2k
-rwxr-xr-x. 1 root root 470336 Aug  4 06:41 /usr/lib64/libssl.so.1.0.2k
```

According to https://www.centos.org/forums/viewtopic.php?t=60336 , it is not possible to install openssl 1.0.0 on a CentOS 7 box.

Do you know what O/S these tests will run on, or how to fix on CentOS 7?

Thanks,

Rich

**Comment by RichardBradley** [comment]
I can work around this by setting `browsers: ['n/a'],` in `karma.conf.js`, then manually connecting a Chrome window to http://localhost:9876/ after Karma prints the following:

```
10 12 2017 23:34:10.159:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
```

(I did try to get Chrome working on CentOS 7, but I don't know the right magic words for that.)

**Comment by bvaughn** [comment]
Hi Richard,

I'm glad you've made progress here!

Sorry for not responding initially. I must have overlooked the message. I was traveling at the time.

Unfortunately I don't have helpful advice anyway! 😅

**Comment by RichardBradley** [comment]
OK, never mind. I can run Karma with a different browser and not commit those changes.

**Comment by RichardBradley** [comment]
I think part of the problem here is a Babel 5 / Babel 6 conflict, similar to: https://github.com/relayjs/relay-starter-kit/issues/74

You have included https://www.npmjs.com/package/babel-plugin-react-transform at version 3.0.0 which is Babel 6, but the rest of your Babel config is for v5.

If I try to run the tests with `mocha` instead of `karma`, I get:

```
$ ./node_modules/.bin/mocha  --compilers js:babel-register "src/**/*.test.js"                ...\node_modules\babel-core\lib\api\node.js:110
  throw new Error("The (" + alias + ") Babel 5 plugin is being run with Babel 6.");
  ^

Error: The (babel-plugin-react-transform) Babel 5 plugin is being run with Babel 6.
```
