### ISSUE TITLE
Error when using the provided example 

### ISSUE THREAD

**Issue by sockol** [bvaughn/react-highlight-words#48]
My mistake - resolved by changing "searchWords" prop into an array

<Highlighter
highlightClassName='YourHighlightClass'
searchWords={['and', 'or', 'the']}
autoEscape={true}
textToHighlight="The dog is chasing the cat. Or perhaps they're just playing?"
/>

**Comment by bvaughn** [comment]
Must be. Works fine for me: https://codesandbox.io/s/5v8yqoxv7k

I'm afraid I can't help with the limited info provided.
