### ISSUE TITLE
Bracket error regexp

### ISSUE THREAD

**Issue by Lemaro86** [bvaughn/react-highlight-words#51]
If textToHighlight have bracket, for example: 
textToHighlight='Hi (friend)'  

I have got error if i remove this bracket: textToHighlight='Hi (friend'

main.js:375 Uncaught SyntaxError: Invalid regular expression: /БАНК "ТАВРИЧЕСКИЙ" (ОАО/: Unterminated group

I think trouble in 'highlight-words-core'  in function escapeRegExpFn

**Comment by Lemaro86** [comment]
autoEscape= true resolve it.
forgive me for dullness

**Comment by bvaughn** [comment]
No worries. Glad you figured it out..

>
