### ISSUE TITLE
Can't highlight in multiple colors

### ISSUE THREAD

**Issue by josiahcoad** [bvaughn/react-highlight-words#53]
I am trying to use React-Highlight-Words to apply two different highlighting styles to words based on if they are "good words" (green highlighting) or "bad" (red highlighting). But from what I can tell, there is only one "searchWords" list you can pass for the Highlight component to apply styling too. How would I go about having two lists for different styling?

**Comment by bvaughn** [comment]
This isn't supported, sorry! 😄

**Comment by josiahcoad** [comment]
Ah, too bad. That would be nice! Any suggestions possibly for packages to do this?

**Comment by bvaughn** [comment]
I don't know of any, but I'm sure there are some. I would just search NPM for tags like "react" and "highlight" or "search".

**Comment by bvaughn** [comment]
Thanks! 😄
