### ISSUE TITLE
Im just looking for help but was ignored

### ISSUE THREAD

**Issue by Albert0405** [bvaughn/react-highlight-words#55]
Don't know what's the problem with the owner of this library. If you cant help, you dont need to lock my issue. Someone might have help me instead but anyway thanks. That will not happen anymore.

**Comment by Albert0405** [comment]
https://github.com/bvaughn/react-highlight-words/issues/54#issuecomment-395976006

**Comment by bvaughn** [comment]
Re-read issue #54.

If you still think you were being reasonable, I don't know what to say.

Please don't open additional issues like this on this repo though.
