### ISSUE TITLE
Add multiple styles from multiple words

### ISSUE THREAD

**Issue by Albert0405** [bvaughn/react-highlight-words#56]
Hi guys you can check my `REACT` code here not `REACT NATIVE` https://codesandbox.io/s/6v1lzor8mz

I wanted to achieve something like this:
![90327d00-3b0a-11e7-9469-e2aa8b13bb8a](https://user-images.githubusercontent.com/38030623/41193713-c62bed50-6c42-11e8-86ff-e7c85e41720c.png)

but as you can see in the result, only the word `What` and `do` has a fontColor of red but also wanted to change the fontColor of the word `after` and `school` to color blue. How can i do that?

**Comment by bvaughn** [comment]
There are "guys" here. This is a personal project. Every issue you post will be answered (or not) by the sole maintainer (me).

What you are showing in the above screen shot (multiple colors for different search terms) is not supported by this library.
