### ISSUE TITLE
Contextual highlight classes

### ISSUE THREAD

**Issue by sjnonweb** [bvaughn/react-highlight-words#58]
- I had a requirement to highlight a few keywords in a sentence depending on their contexts, so a single `highlightClassName` was not sufficient. At the time i didn't have much time so i had it forked and published as an independent package [here](https://www.npmjs.com/package/react-highlight-contextual-words).

- This is how it works.
> Accept a prop `contextualHighlightClasses` which is an array of `highlightClassName` having one-two-one relation with words in `searchWords` and then apply the highlighClass accordingly.

- Let me know if you guys are interested, I will sanitize the code and open a PR.

**Comment by bvaughn** [comment]
I'm pretty comfortable with keeping this library/component simple, like it is. I appreciate the offer though!
