### ISSUE TITLE
Missing typescript typings

### ISSUE THREAD

**Issue by tvthatsme** [bvaughn/react-highlight-words#60]
I'd like to work on this, but it would be helpful if the project included the type definitions for anyone who wants to include this in a project using typescript.

Unless you object, I will raise a PR within a day or two, ... or sooner 😃

**Comment by bvaughn** [comment]
For definitely typed? Sure sounds fine.

**Comment by jsphweid** [comment]
Wait, doesn't this exist here already: https://www.npmjs.com/package/@types/react-highlight-words?

But honestly, I get errors when importing in a typescript project.
```typescript
import * as Highlighter from 'react-highlight-words' // works but with warnings
import Highlighter from 'react-highlight-words' // blows up
import Highlighter from 'react-highlight-words' // doesn't work
const Highlighter = require('react-highlight-words') // works
```

This is how it's exported in the d.ts but it probably isn't quite right? My guess is that this snippet below is the reason why you get warnings when you try the first line in the above code.
```
declare class Highlighter extends React.Component<HighlighterProps> {}
export default Highlighter;
```

**Comment by damiangreen** [comment]
Anyone working on a fix ?

**Comment by bvaughn** [comment]
TypeScript types for this lib should go to the DefinitelyTyped repo, rather than here. The "fix"would be to open a PR there. 😊
