### ISSUE TITLE
SyntaxError: Invalid regular expression: /?/: Nothing to repeat

### ISSUE THREAD

**Issue by Steven24K** [bvaughn/react-highlight-words#67]
When I try to highlight a word that starts with "?" than it throws the following exception: 
![image](https://user-images.githubusercontent.com/22052733/49004647-01439f80-f165-11e8-8b7b-398b3389690b.png)

I don't know if this is a bug or that I am doing something wrong, but the issue seems to be in the npm package.

**Comment by bvaughn** [comment]
Check out the `autoEscape` prop mentioned in [docs](https://github.com/bvaughn/react-highlight-words#props). Should fix things for you!
