### ISSUE TITLE
Keyboard AND Inline calendar

### ISSUE THREAD

**Issue by GMchris** [bvaughn/react-highlight-words#73]
It it possible to display the inline calendar, as well as retain focus on the manual input? When I tab focus to an <InlineDatePicker /> component I'm able to write, but the calendar doesn't appear and if I click on the input field the calendar is there, but I can no longer write in the field.

What I'd love to be able to do is have the calendar appear as an option for people, but retain manual keyboard entry possible (as that's the general expected way for people to enter their dates).

**Comment by bvaughn** [comment]
Hey @GMchris. I think you filed this issue against the wrong project. There's no calendar or input. This is just a component for highlighting text. 😄

**Comment by GMchris** [comment]
@bvaughn Oh wow, sorry. I have no idea how I wound up on this issue page from material-ui-pickers.

**Comment by bvaughn** [comment]
That is pretty funny 😁 no worries though
