### ISSUE TITLE
Binding click/hover events on highlighted words

### ISSUE THREAD

**Issue by HarishSha** [bvaughn/react-highlight-words#79]
Can we bind any event on highlighted word. e.g onClick, onHover, onMouseover, etc

**Comment by akkonrad** [comment]
hey @HarishSha did you solve that?

**Comment by HarishSha** [comment]
Yes I solved that. on click it is opening popup like a word suggestion box. I was extremely busy in switching job and couldn't upload it. 
Will do it by Monday Morning.. Extremely Sorry for late reply.

**Comment by akkonrad** [comment]
you don't have to, actually that can be achieved with the current codebase
by passing the marked element instead of the defalut one.

śr., 2 paź 2019 o 19:52 Harish Kumar <notifications@github.com> napisał(a):

**Comment by lolz0r** [comment]
Can you give an example of this?
