### ISSUE TITLE
Special characters need to be escaped

### ISSUE THREAD

**Issue by tleh** [bvaughn/react-highlight-words#8]
Hi,
if i add the word 'Can.' as a searchword it marks 'Cano', 'Cana', 'Cann' ... 
So the '.' is used as a wildcard
If u search for '.' everything gets marked
i think its wrong behaviour or you need at least a param to turn it off

**Comment by bvaughn** [comment]
The searching/matching is [implemented as a regular expression](https://github.com/bvaughn/react-highlight-words/blob/master/src/utils.js#L53-L65) in which the "." character has special significance. Fortunately you can just escape the "." before passing it in (eg search for "Can\.").

**Comment by bvaughn** [comment]
I don't think I should try to add any auto-escaping in as that would prevent users who _wanted_ to take advantage of full regular expression support from being able to (eg you could search for "c.n" to match "Can" and "con").

**Comment by tleh** [comment]
ok, i'm totally with you that it is a useful function
but i also think it is not wanted in every use case, so a param would be the best tradeoff here, but of couse no need to
but when you think in searching for "George W." it gives you results/highlights you actually don't want (in some use cases)
so it is not an bug but maybe a future improvement

**Comment by bvaughn** [comment]
Hey @tleh! Just a quick follow-up note to let you know that version 0.4.0 now supports this functionality by way of a new `autoEscape` boolean property. Cheers

**Comment by tleh** [comment]
hi @bvaughn, thanks !
