### ISSUE TITLE
How to combine with react-markdown?

### ISSUE THREAD

**Issue by Kadrian** [bvaughn/react-highlight-words#91]
Hi, I'd love to combine using this with `react-markdown`:  https://github.com/rexxars/react-markdown

The problem
1)  `<ReactMarkdown source={text} />` accepts a string text.
2) `<Highlighter textToHighlight={text} />` accepts a string text.

Both render HTML. But how to combine both? 

- How do I highlight text generated from markdown?
- How do I generate markdown from highlighted text?

Any ideas? 🤟

**Comment by Kadrian** [comment]
Okay, got it to work using a text renderer like here https://github.com/rexxars/react-markdown/issues/218#issuecomment-428510740

**Comment by amcdnl** [comment]
@Kadrian - Would love to see your solution.
